package docs

var (
	bakedIn = map[string]Documentor{
		"required":                RuleWithoutValue{DescTemplate: "Field is required"},
		"required_if":             RuleWithFieldValue{DescTemplate: "Field is required if %s"},
		"required_unless":         RuleWithFieldValue{DescTemplate: "Field is required unless %s"},
		"required_with":           RuleWithField{DescTemplate: "Field is required if any of %s is given and not empty", Op: opOr},
		"required_with_all":       RuleWithField{DescTemplate: "Field is required if all of %s is given and not empty"},
		"required_without":        RuleWithField{DescTemplate: "Field is required if any of %s is not given", Op: opOr},
		"required_without_all":    RuleWithField{DescTemplate: "Field is required if none of %s is given"},
		"isdefault":               RuleWithoutValue{DescTemplate: "Field must contain default value"},
		"len":                     RuleWithValue{DescTemplate: "Length must be exactly %s long"},
		"min":                     RuleWithValue{DescTemplate: "Length must be at least %s long"},
		"max":                     RuleWithValue{DescTemplate: "Length must be at most %s long"},
		"eq":                      RuleWithValue{DescTemplate: "Field must be equal to %s"},
		"ne":                      RuleWithValue{DescTemplate: "Field must not be equal to %s"},
		"lt":                      RuleWithValue{DescTemplate: "Field must be less than %s"},
		"lte":                     RuleWithValue{DescTemplate: "Field must be less than or equal to %s"},
		"gt":                      RuleWithValue{DescTemplate: "Field must be greater than %s"},
		"gte":                     RuleWithValue{DescTemplate: "Field must be greater than or equal to %s"},
		"eqfield":                 RuleWithField{DescTemplate: "Field must be equal to %s"},
		"eqcsfield":               RuleWithField{DescTemplate: "Field must be equal to %s"},
		"necsfield":               RuleWithField{DescTemplate: "Field must not be equal to %s"},
		"gtcsfield":               RuleWithField{DescTemplate: "Field must be greater than %s"},
		"gtecsfield":              RuleWithField{DescTemplate: "Field must be greater than %s"},
		"ltcsfield":               RuleWithField{DescTemplate: "Field must be less than %s"},
		"ltecsfield":              RuleWithField{DescTemplate: "Field must be less than %s"},
		"nefield":                 RuleWithField{DescTemplate: "Field must not be equal to %s"},
		"gtefield":                RuleWithField{DescTemplate: "Field must be greater than or equal to %s"},
		"gtfield":                 RuleWithField{DescTemplate: "Field must be greater than %s"},
		"ltefield":                RuleWithField{DescTemplate: "Field must be less than or equal to %s"},
		"ltfield":                 RuleWithField{DescTemplate: "Field must be less than %s"},
		"fieldcontains":           RuleWithValue{DescTemplate: "Field must contain %s"},
		"iscolor":                 RuleWithoutValue{DescTemplate: "Field must be valid color e.g. hexcolor, rgb, rgba, hsl or hsla"},
		"country_code":            RuleWithoutValue{DescTemplate: "Field must be a valid country code"},
		"alpha":                   RuleWithoutValue{DescTemplate: "Field must contain alpha characters"},
		"alphanum":                RuleWithoutValue{DescTemplate: "Field must contain alpha numeric characters"},
		"alphaunicode":            RuleWithoutValue{DescTemplate: "Field must contain alpha unicode characters"},
		"alphanumunicode":         RuleWithoutValue{DescTemplate: "Field must contain alpha numeric unicode characters"},
		"boolean":                 RuleWithoutValue{DescTemplate: "Field must be a boolean"},
		"numeric":                 RuleWithoutValue{DescTemplate: "Field must be numeric"},
		"number":                  RuleWithoutValue{DescTemplate: "Field must be a number"},
		"hexadecimal":             RuleWithoutValue{DescTemplate: "Field must be hexadecimal"},
		"hexcolor":                RuleWithoutValue{DescTemplate: "Field must be in hex color format"},
		"rgb":                     RuleWithoutValue{DescTemplate: "Field must be in rgb color format"},
		"rgba":                    RuleWithoutValue{DescTemplate: "Field must be in rgba color format"},
		"hsl":                     RuleWithoutValue{DescTemplate: "Field must be in hsl color format"},
		"hsla":                    RuleWithoutValue{DescTemplate: "Field must be in hsla color format"},
		"email":                   RuleWithoutValue{DescTemplate: "Field must be a valid email"},
		"url":                     RuleWithoutValue{DescTemplate: "Field must be a valid url"},
		"uri":                     RuleWithoutValue{DescTemplate: "Field must be a valid uri"},
		"urn_rfc2141":             RuleWithoutValue{DescTemplate: "Field must be a valid urn (RFC 2141)"}, // RFC 2141
		"file":                    RuleWithoutValue{DescTemplate: "Field must be a valid file"},
		"base64":                  RuleWithoutValue{DescTemplate: "Field must be base64 encoded string"},
		"base64url":               RuleWithoutValue{DescTemplate: "Field must be base64url encoded string"},
		"contains":                RuleWithValue{DescTemplate: "Field must contain '%s' substring"},
		"containsany":             RuleWithValue{DescTemplate: "Field must contain any of %s characters"},
		"containsrune":            RuleWithValue{DescTemplate: "Field must contain %s"},
		"excludes":                RuleWithValue{DescTemplate: "Field must not contain the '%s' substring"},
		"excludesall":             RuleWithValue{DescTemplate: "Field must not contain any of %s characters"},
		"excludesrune":            RuleWithValue{DescTemplate: "Field must not contain %s"},
		"startswith":              RuleWithValue{DescTemplate: "Field must start with '%s'"},
		"endswith":                RuleWithValue{DescTemplate: "Field must end with '%s'"},
		"startsnotwith":           RuleWithValue{DescTemplate: "Field must not start with '%s'"},
		"endsnotwith":             RuleWithValue{DescTemplate: "Field must not end with '%s'"},
		"isbn":                    RuleWithoutValue{DescTemplate: "Field must be a valid ISBN"},
		"isbn10":                  RuleWithoutValue{DescTemplate: "Field must be a valid ISBN10"},
		"isbn13":                  RuleWithoutValue{DescTemplate: "Field must be a valid ISBN13"},
		"eth_addr":                RuleWithoutValue{DescTemplate: "Field must be a valid ethereum address"},
		"btc_addr":                RuleWithoutValue{DescTemplate: "Field must be a valid bitcoin address"},
		"btc_addr_bech32":         RuleWithoutValue{DescTemplate: "Field must be a valid bitcoin bech32 address (segwit)"},
		"uuid":                    RuleWithoutValue{DescTemplate: "Field must be a valid UUID"},
		"uuid3":                   RuleWithoutValue{DescTemplate: "Field must be a valid UUIDv3"},
		"uuid4":                   RuleWithoutValue{DescTemplate: "Field must be a valid UUIDv4"},
		"uuid5":                   RuleWithoutValue{DescTemplate: "Field must be a valid UUIDv5"},
		"uuid_rfc4122":            RuleWithoutValue{DescTemplate: "Field must be a valid UUID RFC 4122"},
		"uuid3_rfc4122":           RuleWithoutValue{DescTemplate: "Field must be a valid UUIDv3 RFC 4122"},
		"uuid4_rfc4122":           RuleWithoutValue{DescTemplate: "Field must be a valid UUIDv4 RFC 4122"},
		"uuid5_rfc4122":           RuleWithoutValue{DescTemplate: "Field must be a valid UUIDv5 RFC 4122"},
		"ascii":                   RuleWithoutValue{DescTemplate: "Field must be ASCII characters only"},
		"printascii":              RuleWithoutValue{DescTemplate: "Field must be printable ASCII characters"},
		"multibyte":               RuleWithoutValue{DescTemplate: "Field must contain one or more multibyte characters"},
		"datauri":                 RuleWithoutValue{DescTemplate: "Field must be a valid data uri"},
		"latitude":                RuleWithoutValue{DescTemplate: "Field must be a valid latitude"},
		"longitude":               RuleWithoutValue{DescTemplate: "Field must be a valid longitude"},
		"ssn":                     RuleWithoutValue{DescTemplate: "Field must be a valid SSN"},
		"ipv4":                    RuleWithoutValue{DescTemplate: "Field must be a valid IPv4 address"},
		"ipv6":                    RuleWithoutValue{DescTemplate: "Field must be a valid IPv6 address"},
		"ip":                      RuleWithoutValue{DescTemplate: "Field must be a valid IP"},
		"cidrv4":                  RuleWithoutValue{DescTemplate: "Field must be a valid classless inter-domain routing"},
		"cidrv6":                  RuleWithoutValue{DescTemplate: "Field must be a valid v4 classless inter-domain routing"},
		"cidr":                    RuleWithoutValue{DescTemplate: "Field must be a valid v6 classless inter-domain routing"},
		"tcp4_addr":               RuleWithoutValue{DescTemplate: "Field must be a valid TCPv4 address"},
		"tcp6_addr":               RuleWithoutValue{DescTemplate: "Field must be a valid TCPv6 address"},
		"tcp_addr":                RuleWithoutValue{DescTemplate: "Field must be a valid TCP address"},
		"udp4_addr":               RuleWithoutValue{DescTemplate: "Field must be a valid UDPv4 address"},
		"udp6_addr":               RuleWithoutValue{DescTemplate: "Field must be a valid UDPv6 address"},
		"udp_addr":                RuleWithoutValue{DescTemplate: "Field must be a valid UDP address"},
		"ip4_addr":                RuleWithoutValue{DescTemplate: "Field must be a valid IPv4 address"},
		"ip6_addr":                RuleWithoutValue{DescTemplate: "Field must be a valid IPv6 address"},
		"ip_addr":                 RuleWithoutValue{DescTemplate: "Field must be a valid IP address"},
		"unix_addr":               RuleWithoutValue{DescTemplate: "Field must be a valid unix domain socket address"},
		"mac":                     RuleWithoutValue{DescTemplate: "Field must be a valid MAC address"},
		"hostname":                RuleWithoutValue{DescTemplate: "Field must be a valid hostname RFC 952"}, // RFC 952
		"hostname_rfc1123":        RuleWithoutValue{DescTemplate: "Field must be a valid hosname RFC1123"},  // RFC 1123
		"fqdn":                    RuleWithoutValue{DescTemplate: "Field must be a valid full qualified domain name"},
		"unique":                  RuleWithoutValue{DescTemplate: "Field must be unique"},
		"oneof":                   RuleWithValue{DescTemplate: "Field must be one of %s"},
		"html":                    RuleWithoutValue{DescTemplate: "Field must be valid HTML"},
		"html_encoded":            RuleWithoutValue{DescTemplate: "Field must be valid HTML (encoded)"},
		"url_encoded":             RuleWithoutValue{DescTemplate: "Field must be a valid URL (encoded)"},
		"dir":                     RuleWithoutValue{DescTemplate: "Field must be a valid directory on the host machine"},
		"json":                    RuleWithoutValue{DescTemplate: "Field must be valid JSON"},
		"jwt":                     RuleWithoutValue{DescTemplate: "Field must be valid JWT"},
		"hostname_port":           RuleWithoutValue{DescTemplate: "Field must be a valid hostname:port"},
		"lowercase":               RuleWithoutValue{DescTemplate: "Field must consist of lowercase letters"},
		"uppercase":               RuleWithoutValue{DescTemplate: "Field must consist of uppercase letters"},
		"datetime":                RuleWithoutValue{DescTemplate: "Field must be a valid datetime"},
		"timezone":                RuleWithoutValue{DescTemplate: "Field must be a valid timezone, e.g. America/New_York"},
		"postcode_iso3166_alpha2": RuleWithoutValue{DescTemplate: "Field must be a valid postcode"},
		// "excluded_with":                 RuleWithField{DescTemplate: ""},
		// "excluded_with_all":             RuleWithField{DescTemplate: ""},
		// "excluded_without":              RuleWithField{DescTemplate: ""},
		// "excluded_without_all":          RuleWithField{DescTemplate: ""},
		// "fieldexcludes":                 RuleWithoutValue{DescTemplate: ""},
		// "e164":                    RuleWithoutValue{DescTemplate: ""},
		//"iso3166_1_alpha2":              RuleWithoutValue{DescTemplate: ""},
		//"iso3166_1_alpha3":              RuleWithoutValue{DescTemplate: ""},
		//"iso3166_1_alpha_numeric":       RuleWithoutValue{DescTemplate: ""},
		//"iso3166_2":                     RuleWithoutValue{DescTemplate: ""},
		//"iso4217":                       RuleWithoutValue{DescTemplate: ""},
		//"iso4217_numeric":               RuleWithoutValue{DescTemplate: ""},
		//"bcp47_language_tag":            RuleWithoutValue{DescTemplate: ""},
		//"postcode_iso3166_alpha2_field": RuleWithoutValue{DescTemplate: ""},
		//"bic":                           RuleWithoutValue{DescTemplate: ""},
	}
)
