package docs

var (
	bakedIn = map[string]string{
		"required":                      "Field is required",
		"required_if":                   "Field is required if %s",
		"required_unless":               "Field is required unless %s",
		"required_with":                 "",
		"required_with_all":             "",
		"required_without":              "",
		"required_without_all":          "",
		"excluded_with":                 "",
		"excluded_with_all":             "",
		"excluded_without":              "",
		"excluded_without_all":          "",
		"isdefault":                     "",
		"len":                           "Length must be exactly %s long",
		"min":                           "Length must be at least %s long",
		"max":                           "Length must be at most %s long",
		"eq":                            "Field must be equal to %s",
		"ne":                            "Field must not be equal to %s",
		"lt":                            "Field must be less than %s",
		"lte":                           "Field must be less than or equal to %s",
		"gt":                            "Field must be greater than %s",
		"gte":                           "Field must be greater than or equal to %s",
		"eqfield":                       "Field must be equal to the %s field",
		"eqcsfield":                     "Field must be equal to the %s field",
		"necsfield":                     "Field must not be equal to the %s field",
		"gtcsfield":                     "Field must be greater than the %s field",
		"gtecsfield":                    "Field must be greater than the %s field",
		"ltcsfield":                     "Field must be less than the %s field",
		"ltecsfield":                    "Field must be less than the %s field",
		"nefield":                       "Field must not be equal to the %s field",
		"gtefield":                      "",
		"gtfield":                       "",
		"ltefield":                      "",
		"ltfield":                       "",
		"fieldcontains":                 "",
		"fieldexcludes":                 "",
		"iscolor":                       "hexcolor|rgb|rgba|hsl|hsla",
		"country_code":                  "iso3166_1_alpha2|iso3166_1_alpha3|iso3166_1_alpha_numeric",
		"alpha":                         "",
		"alphanum":                      "",
		"alphaunicode":                  "",
		"alphanumunicode":               "",
		"boolean":                       "",
		"numeric":                       "",
		"number":                        "",
		"hexadecimal":                   "",
		"hexcolor":                      "",
		"rgb":                           "",
		"rgba":                          "",
		"hsl":                           "",
		"hsla":                          "",
		"e164":                          "",
		"email":                         "",
		"url":                           "",
		"uri":                           "",
		"urn_rfc2141":                   "", // RFC 2141
		"file":                          "",
		"base64":                        "",
		"base64url":                     "",
		"contains":                      "",
		"containsany":                   "",
		"containsrune":                  "",
		"excludes":                      "",
		"excludesall":                   "",
		"excludesrune":                  "",
		"startswith":                    "",
		"endswith":                      "",
		"startsnotwith":                 "",
		"endsnotwith":                   "",
		"isbn":                          "",
		"isbn10":                        "",
		"isbn13":                        "",
		"eth_addr":                      "",
		"btc_addr":                      "",
		"btc_addr_bech32":               "",
		"uuid":                          "",
		"uuid3":                         "",
		"uuid4":                         "",
		"uuid5":                         "",
		"uuid_rfc4122":                  "",
		"uuid3_rfc4122":                 "",
		"uuid4_rfc4122":                 "",
		"uuid5_rfc4122":                 "",
		"ascii":                         "",
		"printascii":                    "",
		"multibyte":                     "",
		"datauri":                       "",
		"latitude":                      "",
		"longitude":                     "",
		"ssn":                           "",
		"ipv4":                          "",
		"ipv6":                          "",
		"ip":                            "",
		"cidrv4":                        "",
		"cidrv6":                        "",
		"cidr":                          "",
		"tcp4_addr":                     "",
		"tcp6_addr":                     "",
		"tcp_addr":                      "",
		"udp4_addr":                     "",
		"udp6_addr":                     "",
		"udp_addr":                      "",
		"ip4_addr":                      "",
		"ip6_addr":                      "",
		"ip_addr":                       "",
		"unix_addr":                     "",
		"mac":                           "",
		"hostname":                      "", // RFC 952
		"hostname_rfc1123":              "", // RFC 1123
		"fqdn":                          "",
		"unique":                        "",
		"oneof":                         "",
		"html":                          "",
		"html_encoded":                  "",
		"url_encoded":                   "",
		"dir":                           "",
		"json":                          "",
		"jwt":                           "",
		"hostname_port":                 "",
		"lowercase":                     "",
		"uppercase":                     "",
		"datetime":                      "",
		"timezone":                      "",
		"iso3166_1_alpha2":              "",
		"iso3166_1_alpha3":              "",
		"iso3166_1_alpha_numeric":       "",
		"iso3166_2":                     "",
		"iso4217":                       "",
		"iso4217_numeric":               "",
		"bcp47_language_tag":            "",
		"postcode_iso3166_alpha2":       "",
		"postcode_iso3166_alpha2_field": "",
		"bic":                           "",
	}
)
